#???? ??
server:
  port: 8083

  # ?? ?? ?? ?? (1??)
  servlet:
    session:
      timeout: 3600s

# database ?? ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/StockVision?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12345678

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  spring:
    security:
      user:
        name:
        password:
